// Generated by `node scripts/i18n-scan.mjs index`: every catalog file for this language, merged.
import type { Catalog } from "../../translate";
import part01 from "./part01.json";
import part02 from "./part02.json";
import part03 from "./part03.json";
import part04 from "./part04.json";
import part05 from "./part05.json";
import part06 from "./part06.json";
import part07 from "./part07.json";
import part08 from "./part08.json";
import part09 from "./part09.json";
import part10 from "./part10.json";

const catalog: Catalog = { ...part01, ...part02, ...part03, ...part04, ...part05, ...part06, ...part07, ...part08, ...part09, ...part10 };
export default catalog;
