import {
  Combine,
  EyeOff,
  FileImage,
  FileSpreadsheet,
  FileText,
  Images,
  LayoutGrid,
  ListOrdered,
  Lock,
  LockOpen,
  ScanSearch,
  Scissors,
  Sheet,
  Shrink,
  Signature,
  Stamp,
  Bookmark,
  ClipboardPen,
  Contrast,
  Crop,
  FileMinus,
  FilePenLine,
  FilePlus2,
  FileSliders,
  FileX2,
  Hash,
  Layers2,
  PanelTop,
  RotateCw,
  Scaling,
  FileType,
  ImageDown,
  Languages,
  ScanText,
  FileCheck2,
  FileScan,
  FileSearch,
  QrCode,
  ScanEye,
  UserSearch,
  FileCode,
  GitCompareArrows,
  ImageUpscale,
  LetterText,
  Presentation,
  Projector,
  AudioLines,
  Clapperboard,
  Film,
  ImagePlay,
  MapPinOff,
  Minimize2,
  BadgeCheck,
  FileKey,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import { msg } from "@/i18n/msg";
import type { FileKind } from "./files";

export type ToolCategoryId = "privacy" | "inspect" | "edit" | "organize" | "security" | "convert" | "media" | "optimize";

export interface ToolCategory {
  id: ToolCategoryId;
  name: string;
}

export const TOOL_CATEGORIES: ToolCategory[] = [
  { id: "privacy", name: msg("Sanitize & Privacy") },
  { id: "inspect", name: msg("Inspect") },
  { id: "edit", name: msg("Edit & Sign") },
  { id: "organize", name: msg("Organize") },
  { id: "security", name: msg("Security") },
  { id: "convert", name: msg("Convert") },
  { id: "media", name: msg("Audio & Video") },
  { id: "optimize", name: msg("Optimize") },
];

export interface Tool {
  /** URL slug: /tools/<id> */
  id: string;
  name: string;
  description: string;
  category: ToolCategoryId;
  icon: LucideIcon;
  /** Other words people search for this tool by (synonyms, formats, tasks). */
  keywords?: string[];
  /** File kinds this tool can take as input. */
  accepts: FileKind[];
  /** Whether the tool works on several files at once (e.g. merge). */
  multiFile?: boolean;
  /** Flip to "ready" once the tool's workspace is implemented. */
  status: "ready" | "planned";
}

export const TOOLS: Tool[] = [
  {
    id: "sanitize",
    name: msg("Sanitize Metadata"),
    description: msg("Audit hidden metadata (EXIF, XMP, PDF info), strip it in one click, and verify the result is clean."),
    category: "privacy",
    icon: ScanSearch,
    keywords: ["exif", "gps", "location", "privacy", "clean", "remove metadata", "strip", "author", "iphone", "photo", "heic", "xmp", "hidden data"],
    accepts: ["pdf", "image"],
    status: "ready",
  },
  {
    id: "edit-metadata",
    name: msg("Edit Metadata"),
    description: msg("Set a PDF's title, author, subject, keywords and dates to exactly what you want."),
    category: "privacy",
    icon: FileSliders,
    keywords: ["properties", "title", "author", "document info", "keywords", "change metadata"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "find-pii",
    name: msg("Find Personal Data"),
    description: msg("Find email addresses, phone numbers, card and bank account numbers and ID numbers in a PDF, then redact them in one go."),
    category: "inspect",
    icon: UserSearch,
    keywords: ["pii", "personal information", "gdpr", "email", "phone", "credit card", "iban", "ssn", "social security", "national insurance", "sensitive data", "data leak", "dlp"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "inspect-pdf",
    name: msg("Inspect PDF"),
    description: msg("Find what a PDF hides: fake redactions, invisible text, earlier versions, scripts, attachments, comments and hidden layers. Then clean it."),
    category: "inspect",
    icon: FileSearch,
    keywords: ["hidden", "fake redaction", "redaction check", "black box", "invisible text", "white text", "versions", "javascript", "malware", "attachments", "layers", "forensic", "clean pdf"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "inspect-office",
    name: msg("Inspect Office File"),
    description: msg("Find names, comments, tracked changes, hidden sheets, speaker notes and file paths in Word, Excel and PowerPoint files, and remove them."),
    category: "inspect",
    icon: FileScan,
    keywords: ["word", "excel", "powerpoint", "docx", "xlsx", "pptx", "tracked changes", "comments", "hidden sheets", "speaker notes", "document inspector", "remove personal information", "author"],
    accepts: ["word", "excel", "powerpoint"],
    status: "ready",
  },
  {
    id: "image-forensics",
    name: msg("Image Forensics"),
    description: msg("Look for signs a photo was edited or made with AI: editing apps, AI labels, Content Credentials, a mismatched thumbnail and error levels."),
    category: "inspect",
    icon: ScanEye,
    keywords: ["fake photo", "photoshopped", "edited", "ai generated", "deepfake", "ela", "error level", "c2pa", "content credentials", "authenticity", "verify photo"],
    accepts: ["image"],
    status: "ready",
  },
  {
    id: "check-file",
    name: msg("Check File & Hashes"),
    description: msg("See what any file really is, whatever its name says, spot disguised programs, and get its SHA-256, SHA-1 and MD5 hashes."),
    category: "inspect",
    icon: FileCheck2,
    keywords: ["file type", "extension", "virus", "malware", "exe", "hash", "checksum", "sha256", "sha-256", "md5", "verify download", "integrity", "magic bytes"],
    accepts: ["pdf", "image", "word", "excel", "powerpoint", "text", "video", "audio", "unknown"],
    status: "ready",
  },
  {
    id: "check-links",
    name: msg("Check Links & QR Codes"),
    description: msg("Check every link and QR code in a PDF or picture for phishing tricks, without visiting them."),
    category: "inspect",
    icon: QrCode,
    keywords: ["phishing", "qr code", "url", "scam", "link checker", "quishing", "suspicious link", "fake website"],
    accepts: ["pdf", "image"],
    status: "ready",
  },
  {
    id: "compare-pdf",
    name: msg("Compare PDFs"),
    description: msg("See what changed between two versions of a PDF: words added, removed and changed, or a picture-by-picture comparison."),
    category: "inspect",
    icon: GitCompareArrows,
    keywords: ["diff", "difference", "changes", "versions", "revision", "redline", "track changes", "contract", "compare documents"],
    accepts: ["pdf"],
    multiFile: true,
    status: "ready",
  },
  {
    id: "edit-pdf",
    name: msg("Edit PDF"),
    description: msg("Add and edit text, white out, highlight, draw, add shapes, check marks, images, signatures and notes, all on one page."),
    category: "edit",
    icon: FilePenLine,
    keywords: ["edit text", "add text", "annotate", "highlight", "underline", "strikethrough", "draw", "pen", "whiteout", "erase", "shapes", "rectangle", "arrow", "check mark", "tick", "cross", "image", "sticky note", "comment", "typewriter", "fill"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "fill-pdf",
    name: msg("Fill PDF Form"),
    description: msg("Type into a PDF form's fields, tick its boxes and pick its options, then save it, optionally flattened."),
    category: "edit",
    icon: ClipboardPen,
    keywords: ["form", "fill in", "fillable", "acroform", "fields", "application"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "header-footer",
    name: msg("Header & Footer"),
    description: msg("Add text at the top and bottom of pages, with page numbers, the date or the file name."),
    category: "edit",
    icon: PanelTop,
    keywords: ["header", "footer", "running head", "page x of y", "date", "file name"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "bates",
    name: msg("Bates Numbering"),
    description: msg("Number every page of one or more PDFs in one sequence, e.g. ACME-000001, for legal and audit work."),
    category: "edit",
    icon: Hash,
    keywords: ["legal", "discovery", "stamp numbers", "sequence", "exhibit"],
    accepts: ["pdf"],
    multiFile: true,
    status: "ready",
  },
  {
    id: "flatten",
    name: msg("Flatten PDF"),
    description: msg("Make form answers, comments, highlights and stamps part of the page so they can't be changed."),
    category: "edit",
    icon: Layers2,
    keywords: ["lock form", "flatten annotations", "merge layers", "non editable"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "bookmarks",
    name: msg("Bookmarks"),
    description: msg("Add, rename, nest and reorder the bookmarks (outline) readers show beside a PDF."),
    category: "edit",
    icon: Bookmark,
    keywords: ["outline", "table of contents", "toc", "navigation", "chapters"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "merge",
    name: msg("Merge PDF"),
    description: msg("Combine several PDFs into one document in the order you choose."),
    category: "organize",
    icon: Combine,
    keywords: ["combine", "join", "append", "put together"],
    accepts: ["pdf"],
    multiFile: true,
    status: "ready",
  },
  {
    id: "split",
    name: msg("Split PDF"),
    description: msg("Extract page ranges or split a PDF into separate files."),
    category: "organize",
    icon: Scissors,
    keywords: ["extract pages", "separate", "divide", "cut", "pages"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "organize",
    name: msg("Organize Pages"),
    description: msg("Reorder, rotate and delete pages on a visual drag-and-drop grid."),
    category: "organize",
    icon: LayoutGrid,
    keywords: ["reorder", "rotate", "delete pages", "remove pages", "sort", "arrange", "move pages"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "batch",
    name: msg("Batch Process"),
    description: msg("Run several tools one after another on all your open files (clean, stamp, convert, protect, sign) and download the results together."),
    category: "organize",
    icon: Workflow,
    keywords: ["batch", "bulk", "many files", "multiple files", "all files", "at once", "automate", "action wizard", "workflow", "sequence", "steps", "recipe"],
    accepts: ["pdf", "image", "word", "excel", "powerpoint", "text", "video", "audio"],
    multiFile: true,
    status: "ready",
  },
  {
    id: "rotate",
    name: msg("Rotate PDF"),
    description: msg("Turn all pages or just the ones you pick, by 90° or 180°."),
    category: "organize",
    icon: RotateCw,
    keywords: ["turn", "orientation", "sideways", "upside down", "landscape"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "delete-pages",
    name: msg("Delete Pages"),
    description: msg("Remove the pages you pick; they're purged from the file, not just hidden."),
    category: "organize",
    icon: FileMinus,
    keywords: ["remove pages", "delete", "drop pages"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "insert-pages",
    name: msg("Insert Pages"),
    description: msg("Add blank pages, or pages from another PDF, anywhere in a document."),
    category: "organize",
    icon: FilePlus2,
    keywords: ["add pages", "blank page", "insert"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "crop",
    name: msg("Crop PDF"),
    description: msg("Trim page edges by hand or remove white margins automatically."),
    category: "organize",
    icon: Crop,
    keywords: ["trim", "margins", "white space", "cut edges"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "resize-pages",
    name: msg("Resize Pages"),
    description: msg("Change the paper size (A4, Letter, Legal, A3, A5 or custom), scaling content to fit."),
    category: "organize",
    icon: Scaling,
    keywords: ["page size", "a4", "letter", "paper size", "scale"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "remove-blank",
    name: msg("Remove Blank Pages"),
    description: msg("Find blank pages, including scanned ones, and remove them in one go."),
    category: "organize",
    icon: FileX2,
    keywords: ["empty pages", "blank", "scanner", "clean up"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "protect",
    name: msg("Protect PDF"),
    description: msg("Encrypt a PDF with a password (AES-256) and control printing and copying."),
    category: "security",
    icon: Lock,
    keywords: ["password", "encrypt", "lock", "secure", "aes"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "unlock",
    name: msg("Unlock PDF"),
    description: msg("Remove the password or restrictions from a PDF you have access to."),
    category: "security",
    icon: LockOpen,
    keywords: ["remove password", "decrypt", "open locked", "unprotect"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "redact",
    name: msg("Redact PDF"),
    description: msg("Black out sensitive areas and permanently remove the content underneath."),
    category: "security",
    icon: EyeOff,
    keywords: ["black out", "censor", "hide text", "blackout", "remove text", "confidential"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "images-to-pdf",
    name: msg("Images to PDF"),
    description: msg("Turn JPG, PNG, WebP, HEIC and AVIF images into a single PDF."),
    category: "convert",
    icon: FileImage,
    keywords: ["jpg to pdf", "png to pdf", "photo to pdf", "heic to pdf", "scan", "pictures"],
    accepts: ["image"],
    multiFile: true,
    status: "ready",
  },
  {
    id: "heic-to-jpg",
    name: msg("HEIC to JPG"),
    description: msg("Convert iPhone HEIC photos, and AVIF, WebP or PNG images, to JPG or PNG. Location and camera details aren't copied."),
    category: "convert",
    icon: ImageDown,
    keywords: ["iphone", "photo", "heif", "jpeg"],
    accepts: ["image"],
    multiFile: true,
    status: "ready",
  },
  {
    id: "convert-image",
    name: msg("Convert & Resize Images"),
    description: msg("Convert images to JPG, PNG, WebP, BMP, TIFF, ICO or AVIF (where the browser can write it), and resize them. Location and camera details aren't copied."),
    category: "convert",
    icon: ImageUpscale,
    keywords: ["image converter", "resize", "scale", "shrink photo", "webp", "avif", "bmp", "tiff", "ico", "favicon", "icon", "png to jpg", "jpg to png", "dimensions"],
    accepts: ["image"],
    multiFile: true,
    status: "ready",
  },
  {
    id: "pdf-to-images",
    name: msg("PDF to Images"),
    description: msg("Export every page of a PDF as a JPG, PNG or WebP image."),
    category: "convert",
    icon: Images,
    keywords: ["pdf to jpg", "pdf to png", "export pages", "screenshot", "picture"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "pdf-to-word",
    name: msg("PDF to Word"),
    description: msg("Extract the text of a PDF into an editable .docx document."),
    category: "convert",
    icon: FileText,
    keywords: ["docx", "doc", "editable", "text", "convert"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "pdf-to-excel",
    name: msg("PDF to Excel"),
    description: msg("Extract tables from a PDF into an .xlsx spreadsheet."),
    category: "convert",
    icon: FileSpreadsheet,
    keywords: ["xlsx", "table", "spreadsheet", "csv", "convert"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "word-to-pdf",
    name: msg("Word to PDF"),
    description: msg("Convert a .docx document to PDF, keeping headings, lists, tables and images."),
    category: "convert",
    icon: FileType,
    keywords: ["docx", "doc", "document", "convert"],
    accepts: ["word"],
    status: "ready",
  },
  {
    id: "excel-to-pdf",
    name: msg("Excel to PDF"),
    description: msg("Turn Excel, OpenDocument or CSV sheets into paginated PDF tables."),
    category: "convert",
    icon: Sheet,
    keywords: ["xlsx", "csv", "spreadsheet", "ods", "convert"],
    accepts: ["excel"],
    status: "ready",
  },
  {
    id: "ocr",
    name: msg("OCR PDF"),
    description: msg("Recognise the text in scanned PDFs and photos, in 24 languages, to make them searchable and copyable or save it as text."),
    category: "convert",
    icon: ScanText,
    keywords: ["scan", "scanned", "searchable", "recognize text", "recognise", "image to text", "extract text", "copy text", "photo to text", "tesseract", "txt"],
    accepts: ["pdf", "image"],
    status: "ready",
  },
  {
    id: "translate",
    name: msg("Translate PDF"),
    description: msg("Translate a PDF into another language with your browser's built-in translator, keeping its layout. Nothing is sent online."),
    category: "convert",
    icon: Languages,
    keywords: ["translation", "language", "english", "spanish", "french", "german", "arabic", "chinese", "localize", "foreign"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "pdf-to-pptx",
    name: msg("PDF to PowerPoint"),
    description: msg("Turn each page of a PDF into a slide, with its text in editable text boxes or as a picture of the page."),
    category: "convert",
    icon: Presentation,
    keywords: ["pptx", "ppt", "slides", "presentation", "keynote", "google slides", "deck", "convert"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "pptx-to-pdf",
    name: msg("PowerPoint to PDF"),
    description: msg("Convert a .pptx presentation to PDF, one page per slide, with its text, shapes, pictures and tables."),
    category: "convert",
    icon: Projector,
    keywords: ["pptx", "ppt", "slides", "presentation", "deck", "handout", "convert"],
    accepts: ["powerpoint"],
    status: "ready",
  },
  {
    id: "pdf-to-text",
    name: msg("PDF to Text & Markdown"),
    description: msg("Extract a PDF's text as plain text or Markdown, with headings, lists and tables rebuilt."),
    category: "convert",
    icon: LetterText,
    keywords: ["txt", "md", "markdown", "extract text", "copy text", "plain text", "notes", "obsidian", "llm", "chatgpt"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "text-to-pdf",
    name: msg("Markdown & HTML to PDF"),
    description: msg("Turn Markdown, HTML or plain-text files into a clean, paginated PDF. Nothing is fetched from the web."),
    category: "convert",
    icon: FileCode,
    keywords: ["md", "markdown", "html", "htm", "web page", "txt", "text to pdf", "readme", "notes", "print"],
    accepts: ["text"],
    status: "ready",
  },
  {
    id: "compress",
    name: msg("Compress PDF"),
    description: msg("Shrink a PDF by downscaling and re-encoding its embedded images."),
    category: "optimize",
    icon: Shrink,
    keywords: ["reduce size", "shrink", "smaller", "optimize", "email"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "grayscale",
    name: msg("Grayscale PDF"),
    description: msg("Turn a PDF's text, drawings and photos gray, for printing without colour ink."),
    category: "optimize",
    icon: Contrast,
    keywords: ["black and white", "monochrome", "greyscale", "no colour", "print"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "sign",
    name: msg("E-Sign PDF"),
    description: msg("Draw or upload a signature and place it anywhere on a page."),
    category: "edit",
    icon: Signature,
    keywords: ["signature", "e-sign", "esign", "sign document", "draw signature", "handwritten", "date", "initials"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "watermark",
    name: msg("Watermark"),
    description: msg("Stamp text or an image on every page, or just the pages you pick."),
    category: "edit",
    icon: Stamp,
    keywords: ["stamp", "draft", "confidential", "logo", "overlay"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "page-numbers",
    name: msg("Page Numbers"),
    description: msg("Add page numbers with your choice of position and format."),
    category: "edit",
    icon: ListOrdered,
    keywords: ["number pages", "footer", "header", "pagination", "page x of y"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "digital-signature",
    name: msg("Digital Signature"),
    description: msg("Sign a PDF with a certificate (.p12 or .pfx) so anyone can check who signed it and that nothing changed since. No certificate? Make one here."),
    category: "edit",
    icon: FileKey,
    keywords: ["certificate", "p12", "pfx", "digital id", "pades", "cryptographic", "certify", "sign with certificate", "self-signed", "eidas", "adobe"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "verify-signatures",
    name: msg("Verify Signatures"),
    description: msg("Check the digital signatures in a PDF: who signed it and when, whether anything changed since, and what their certificate says."),
    category: "inspect",
    icon: BadgeCheck,
    keywords: ["validate signature", "check signature", "signed pdf", "digital signature", "certificate", "tampered", "authentic", "pades", "timestamp", "certified"],
    accepts: ["pdf"],
    status: "ready",
  },
  {
    id: "clean-media",
    name: msg("Remove Video & Audio Metadata"),
    description: msg("Find and remove the location, phone model, dates and names hidden in videos and recordings, without re-encoding them."),
    category: "privacy",
    icon: MapPinOff,
    keywords: ["video metadata", "strip", "location", "gps video", "exif video", "mp4", "mov", "mp3 tags", "id3", "phone video", "anonymize", "clean"],
    accepts: ["video", "audio"],
    status: "ready",
  },
  {
    id: "convert-video",
    name: msg("Convert Video"),
    description: msg("Convert videos to MP4, WebM, MOV or MKV, with a smaller resolution or frame rate, or without the sound."),
    category: "media",
    icon: Film,
    keywords: ["video converter", "mov to mp4", "mkv to mp4", "avi to mp4", "webm", "hevc", "h264", "720p", "1080p", "resolution", "mute", "remove sound"],
    accepts: ["video"],
    status: "ready",
  },
  {
    id: "compress-video",
    name: msg("Compress Video"),
    description: msg("Make a video smaller: choose a quality, or a target size for email and chat apps, and a resolution."),
    category: "media",
    icon: Minimize2,
    keywords: ["reduce video size", "shrink video", "smaller video", "email", "whatsapp", "discord", "target size", "mb", "mp4"],
    accepts: ["video"],
    status: "ready",
  },
  {
    id: "convert-audio",
    name: msg("Convert Audio"),
    description: msg("Convert music and recordings to MP3, M4A, WAV, FLAC, OGG or Opus, or save the sound from a video."),
    category: "media",
    icon: AudioLines,
    keywords: ["audio converter", "mp3", "wav to mp3", "m4a to mp3", "extract audio", "video to mp3", "mp4 to mp3", "flac", "voice memo", "normalize", "volume", "bitrate"],
    accepts: ["audio", "video"],
    status: "ready",
  },
  {
    id: "trim-media",
    name: msg("Trim Video & Audio"),
    description: msg("Cut a video or recording down to the part you want: instantly without re-encoding, or exactly to the frame."),
    category: "media",
    icon: Clapperboard,
    keywords: ["cut video", "cut audio", "clip", "shorten", "start", "end", "ringtone", "split video"],
    accepts: ["video", "audio"],
    status: "ready",
  },
  {
    id: "video-to-gif",
    name: msg("Video to GIF"),
    description: msg("Turn a video clip into an animated GIF, or a much smaller animated WebP."),
    category: "media",
    icon: ImagePlay,
    keywords: ["gif maker", "animated gif", "animation", "mp4 to gif", "webp", "meme"],
    accepts: ["video"],
    status: "ready",
  },
];

export function getTool(id: string): Tool | undefined {
  return TOOLS.find((tool) => tool.id === id);
}

export function toolsInCategory(category: ToolCategoryId): Tool[] {
  return TOOLS.filter((tool) => tool.category === category);
}

/**
 * Tools matching a search, best first. Every word must match the tool's name, keywords,
 * description or category; matches in the name count most.
 */
export function searchTools(query: string, translate?: (text: string) => string): Tool[] {
  const words = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (words.length === 0) return TOOLS.filter((t) => t.status === "ready");
  // In another interface language, the translated name and description match as well as the English.
  const both = (text: string) => (translate && translate(text) !== text ? `${text} | ${translate(text)}` : text);
  const scored = TOOLS.filter((t) => t.status === "ready").map((tool) => {
    const name = both(tool.name).toLowerCase();
    const keywords = (tool.keywords ?? []).join(" | ").toLowerCase();
    const description = both(tool.description).toLowerCase();
    const category = both(TOOL_CATEGORIES.find((c) => c.id === tool.category)!.name).toLowerCase();
    let score = 0;
    for (const word of words) {
      const inName = name.split(/[^\p{L}\p{N}]+/u).some((part) => part.startsWith(word)) ? 6 : name.includes(word) ? 4 : 0;
      const inKeywords = keywords.split(/[^\p{L}\p{N}-]+/u).some((part) => part.startsWith(word)) ? 3 : keywords.includes(word) ? 2 : 0;
      const elsewhere = description.includes(word) || category.includes(word) ? 1 : 0;
      const best = Math.max(inName, inKeywords, elsewhere);
      if (best === 0) return { tool, score: 0 };
      score += best;
    }
    // A phrase match ("pdf to word") beats the same words scattered around.
    if (name.includes(words.join(" "))) score += 4;
    // …and "pptx to pdf" names the direction: prefer the tool whose id reads the same way.
    if (tool.id.includes(words.join("-"))) score += 4;
    const positions = words.map((word) => name.indexOf(word));
    if (words.length > 1 && positions.every((p, i) => p >= 0 && (i === 0 || p > positions[i - 1]))) score += 2;
    return { tool, score };
  });
  return scored
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((s) => s.tool);
}

export function toolsAccepting(kind: FileKind): Tool[] {
  return TOOLS.filter((tool) => tool.accepts.includes(kind));
}
